x = vector("numeric", 6)
print("Numeric Type:")
print(x)
c = vector("complex", 6)
print("Complex Type:")
print(c)
l = vector("logical", 6)
print("Logical Type:")
print(l)
chr = vector("character", 6)
print("Character Type:")
print(chr)
